### ISSUE TITLE
Scrolling page issues

### ISSUE THREAD

**Issue by tigrenok00** [themyth92/ngx-lightbox#27] opened 2019-07-08 05:51 UTC
Hi,
I have a gallery of photos which of course can be scrolled, and a lightbox opened on photo clicked. The problem is that when lightbox opens, the whole page scroll jumps back to top. Unless disableScrolling is set to false. However, I do want the scrolling to be disabled, because otherwise it scrolls the page together with the lightbox.
In summary, I want to to use disableScrolling  = true, but the page should stay at the same scroll position which was at the moment the lightbox was opened.

**Comment by themyth92** [comment] 2019-07-11 07:01
Hi there, sorry as nowadays I am very busy and not have time to look at these issues. Will try to do it but if you can have PR to fix this, it will be more than welcomed. Thanks

**Comment by eyho** [comment] 2019-07-17 22:26
Overriding
```
html.lb-disable-scrolling {
  position: initial;
}
```
might solve the problem somewhat, however, there's a reason that the position is set to fixed in lightbox.css, as the author's comment says; the scrolling may broke if you're browsing on iOS. Couldn't reproduce though since I don't have iPhone.

**Comment by themyth92** [comment] 2019-07-19 04:12
should be fixed on 2.0.1

**Closed** 2019-07-25 02:29 UTC
